version: '3'

services:
  my-app:
    container_name: my-app
    build:
      context: ./my-app
      dockerfile: Dockerfile.prod
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)
  my-api:
    container_name: my-api
    build:
      context: ./my-api
      dockerfile: Dockerfile

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true