version: '3'

services:
  my-app:
    container_name: my-app
    image: ghcr.io/fredericlauss/fullnextapp-app:main

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - my-api

  # Add more containers below (nginx, postgres, etc.)
  my-api:
      container_name: my-api
      image: ghcr.io/fredericlauss/fullnextapp-api:main

      # Set envrionment variables based on the .env file
      env_file:
        - .env
      restart: always
      ports:
        - 5000:5000
      depends_on:
        - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=userAdmin
      - MONGO_INITDB_ROOT_PASSWORD=userPassword
    volumes:
      - ./data:/data/db
    command: mongod --quiet --logpath /dev/null 
    